"""Add schedule config

Revision ID: 6932a70a5825
Revises: e02d84e578ab
Create Date: 2026-04-24 12:23:40.447592

"""
from alembic import op
import sqlalchemy as sa


revision = '6932a70a5825'
down_revision = 'e02d84e578ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('periods_per_day', sa.Integer(), nullable=False),
    sa.Column('period_times', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_configs_id'), 'schedule_configs', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_configs_institution_id'), 'schedule_configs', ['institution_id'], unique=True)
    
    # Backfill default schedule configs for any existing institutions
    op.execute("""
        INSERT INTO schedule_configs (institution_id, working_days, periods_per_day, period_times)
        SELECT 
            id, 
            '["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]'::json, 
            7, 
            '{"1": "09:10-10:00", "2": "10:00-10:50", "3": "11:00-11:50", "4": "11:50-12:40", "5": "13:30-14:20", "6": "14:20-15:10", "7": "15:10-16:00"}'::json
        FROM institutions
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_configs_institution_id'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_id'), table_name='schedule_configs')
    op.drop_table('schedule_configs')
    # ### end Alembic commands ###
