"""Add purpose to invites and audit log index

Revision ID: b19b372f3493
Revises: 3221d05683b0
Create Date: 2026-04-25 01:03:06.744679

"""
from alembic import op
import sqlalchemy as sa


revision = 'b19b372f3493'
down_revision = '3221d05683b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('purpose', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'purpose')
    # ### end Alembic commands ###
