"""Add multi-tenancy

Revision ID: e02d84e578ab
Revises: c0546f386801
Create Date: 2026-04-24 12:09:22.299449

"""
from alembic import op
import sqlalchemy as sa


revision = 'e02d84e578ab'
down_revision = 'c0546f386801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=True)
    op.create_index(op.f('ix_institutions_slug'), 'institutions', ['slug'], unique=True)
    
    # Create default institution
    op.execute(
        "INSERT INTO institutions (name, slug, is_active) VALUES ('Default Institution', 'default', true)"
    )

    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_email'), 'invites', ['email'], unique=False)
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_index(op.f('ix_invites_institution_id'), 'invites', ['institution_id'], unique=False)
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    
    # Add nullable institution_id columns
    op.add_column('assignments', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('batches', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('constraints', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('faculty', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('timetable_slots', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('firebase_uid', sa.String(), nullable=True))
    
    # Backfill records
    op.execute("UPDATE assignments SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE batches SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE constraints SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE faculty SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE rooms SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE subjects SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE timetable_slots SET institution_id = (SELECT id FROM institutions WHERE slug='default')")
    op.execute("UPDATE users SET institution_id = (SELECT id FROM institutions WHERE slug='default')")

    # Alter to not nullable
    op.alter_column('assignments', 'institution_id', nullable=False)
    op.alter_column('batches', 'institution_id', nullable=False)
    op.alter_column('constraints', 'institution_id', nullable=False)
    op.alter_column('faculty', 'institution_id', nullable=False)
    op.alter_column('rooms', 'institution_id', nullable=False)
    op.alter_column('subjects', 'institution_id', nullable=False)
    op.alter_column('timetable_slots', 'institution_id', nullable=False)
    op.alter_column('users', 'institution_id', nullable=False)

    # Rest of autogenerated commands
    op.drop_constraint('uq_assignment', 'assignments', type_='unique')
    op.create_unique_constraint('uq_assignment', 'assignments', ['institution_id', 'faculty_id', 'subject_id', 'batch_id'])
    op.create_index(op.f('ix_assignments_institution_id'), 'assignments', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'institutions', ['institution_id'], ['id'])
    
    op.create_index(op.f('ix_batches_institution_id'), 'batches', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'batches', 'institutions', ['institution_id'], ['id'])
    
    op.create_index(op.f('ix_constraints_institution_id'), 'constraints', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'constraints', 'institutions', ['institution_id'], ['id'])
    
    op.drop_constraint('faculty_email_key', 'faculty', type_='unique')
    op.create_index(op.f('ix_faculty_institution_id'), 'faculty', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'faculty', 'institutions', ['institution_id'], ['id'])
    
    op.drop_index('ix_rooms_room_number', table_name='rooms')
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=False)
    op.create_index(op.f('ix_rooms_institution_id'), 'rooms', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'rooms', 'institutions', ['institution_id'], ['id'])
    
    op.drop_index('ix_subjects_code', table_name='subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_index(op.f('ix_subjects_institution_id'), 'subjects', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'institutions', ['institution_id'], ['id'])
    
    op.create_index(op.f('ix_timetable_slots_institution_id'), 'timetable_slots', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'timetable_slots', 'institutions', ['institution_id'], ['id'])
    
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'institution_id')
    op.drop_constraint(None, 'timetable_slots', type_='foreignkey')
    op.drop_index(op.f('ix_timetable_slots_institution_id'), table_name='timetable_slots')
    op.drop_column('timetable_slots', 'institution_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_institution_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_index('ix_subjects_code', 'subjects', ['code'], unique=True)
    op.drop_column('subjects', 'institution_id')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_institution_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.create_index('ix_rooms_room_number', 'rooms', ['room_number'], unique=True)
    op.drop_column('rooms', 'institution_id')
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.drop_index(op.f('ix_faculty_institution_id'), table_name='faculty')
    op.create_unique_constraint('faculty_email_key', 'faculty', ['email'])
    op.drop_column('faculty', 'institution_id')
    op.drop_constraint(None, 'constraints', type_='foreignkey')
    op.drop_index(op.f('ix_constraints_institution_id'), table_name='constraints')
    op.drop_column('constraints', 'institution_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_institution_id'), table_name='batches')
    op.drop_column('batches', 'institution_id')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_institution_id'), table_name='assignments')
    op.drop_constraint('uq_assignment', 'assignments', type_='unique')
    op.create_unique_constraint('uq_assignment', 'assignments', ['faculty_id', 'subject_id', 'batch_id'])
    op.drop_column('assignments', 'institution_id')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_index(op.f('ix_invites_institution_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_email'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_institutions_slug'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
