"""Add grouping_scheme

Revision ID: f1295d1d1ab6
Revises: 6932a70a5825
Create Date: 2026-04-24 12:29:19.716785

"""
from alembic import op
import sqlalchemy as sa


revision = 'f1295d1d1ab6'
down_revision = '6932a70a5825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('grouping_scheme', sa.String(), server_default='batch', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'grouping_scheme')
    # ### end Alembic commands ###
